# Generated by Django 2.2.7 on 2019-11-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augsdapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='CourseCode',
            new_name='courseCode',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='CourseName',
            new_name='courseName',
        ),
        migrations.RemoveField(
            model_name='course',
            name='CompreDateTime',
        ),
        migrations.RemoveField(
            model_name='course',
            name='MidsemDateTime',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Sections',
        ),
        migrations.AddField(
            model_name='course',
            name='compreDateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='midsemDateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
