# Generated by Django 2.2.7 on 2019-11-12 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('augsdapp', '0002_auto_20191112_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='compreDateTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseIC',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='midsemDateTime',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='augsdapp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='SecClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='L2, T3, P2, or other relevant name', max_length=2)),
                ('secType', models.CharField(choices=[('L', 'Lecture'), ('T', 'Tutorial'), ('P', 'Practical')], max_length=1)),
                ('days', models.CharField(max_length=7)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('instructor', models.ForeignKey(null=True, on_delete='SET_NULL', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='augsdapp.Room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='augsdapp.Section')),
            ],
        ),
    ]
