# Generated by Django 2.2.7 on 2019-11-12 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('augsdapp', '0003_auto_20191112_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secclass',
            name='section',
        ),
        migrations.AddField(
            model_name='secclass',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='augsdapp.Course'),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
