# Generated by Django 2.2.7 on 2019-11-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augsdapp', '0004_auto_20191112_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='compreDateTime',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseCode',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='midsemDateTime',
            field=models.DateTimeField(unique=True),
        ),
    ]
