# Generated by Django 2.2.7 on 2019-11-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augsdapp', '0005_auto_20191113_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseName',
            field=models.CharField(max_length=100),
        ),
    ]
