# Generated by Django 2.2.5 on 2019-11-13 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('augsdapp', '0006_auto_20191113_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructorId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='location',
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='LT-1', help_text='LT-1,C-301,A-501,DLT-5', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='secclass',
            name='capacity',
            field=models.IntegerField(help_text='approximate number of students in class', null=True),
        ),
        migrations.AlterField(
            model_name='secclass',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', to='augsdapp.Instructor'),
        ),
    ]
