# Generated by Django 2.2.7 on 2019-11-13 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augsdapp', '0007_auto_20191113_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secclass',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', to=settings.AUTH_USER_MODEL),
        ),
    ]
