# Generated by Django 2.2.5 on 2019-11-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augsdapp', '0008_auto_20191113_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secclass',
            name='capacity',
        ),
        migrations.AddField(
            model_name='secclass',
            name='classSize',
            field=models.IntegerField(help_text='Approximate number of students in class', null=True),
        ),
    ]
