# Generated by Django 2.2.7 on 2019-11-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augsdapp', '0009_auto_20191116_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='days',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='secclass',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', to='augsdapp.Instructor'),
        ),
    ]
